### ISSUE TITLE
DNASp: Error creating window handle

### ISSUE THREAD

**Issue by jaum20** [pegi3s/dockerfiles#18]
I used the command descibed here:https://hub.docker.com/r/pegi3s/dnasp-v6 and got this error:

I'm using Linux Mint 20.3 5.8.0-25-generic

```
No protocol specified

Unhandled Exception: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Error creating window handle. ---> System.ComponentModel.Win32Exception: Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.ToolStripDropDown.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.PointToScreen(Point p)
   at System.Windows.Forms.ToolStripItem.TranslatePoint(Point fromPoint, ToolStripPointType fromPointType, ToolStripPointType toPointType)
   at System.Windows.Forms.ToolStripDropDownItem.DropDownDirectionToDropDownBounds(ToolStripDropDownDirection dropDownDirection, Rectangle dropDownBounds)
   at System.Windows.Forms.ToolStripDropDownItem.GetDropDownBounds(ToolStripDropDownDirection dropDownDirection)
   at System.Windows.Forms.ToolStripDropDownItem.get_DropDownDirection()
   at System.Windows.Forms.ToolStripDropDownItem.get_DropDownLocation()
   at System.Windows.Forms.ToolStripDropDown.GetDropDownBounds(Rectangle suggestedBounds)
   at System.Windows.Forms.ToolStripDropDown.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.SetBounds(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.set_Size(Size value)
   at System.Windows.Forms.ToolStripDropDownMenu.CalculateInternalLayoutMetrics()
   at System.Windows.Forms.ToolStripDropDownMenu.OnLayout(LayoutEventArgs e)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.PerformLayout()
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at System.Windows.Forms.ToolStripItemCollection.AddRange(ToolStripItem[] toolStripItems)
   at DnaSP6.mdidnasp.InitializeComponent()
   at DnaSP6.mdidnasp..ctor()
   --- End of inner exception stack trace ---
   at DnaSP6.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at DnaSP6.mdidnasp.Main()
```

**Comment by hlfernandez** [comment]
Dear @jaum20, as the Docker Hub documentation says: If the command fails, try running `xhost +` first. I have just tried in my computer and the command works fine after running `xhost +`, so I close the issue. Thanks four your interest in  our project!
